// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k8sclient} from '../models';
import {main} from '../models';

export function AIResourceContext(arg1:string,arg2:string,arg3:string):Promise<k8sclient.AIContext>;

export function AddHelmRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AppVersion():Promise<string>;

export function ApplyPreview(arg1:string):Promise<k8sclient.ApplyDiff>;

export function ApplyYAMLOwned(arg1:string,arg2:string):Promise<string>;

export function AskAboutResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<main.AIMessage>):Promise<string>;

export function BrowseHelmRepo(arg1:string):Promise<Array<k8sclient.ChartSearchResult>>;

export function CanI(arg1:string,arg2:string):Promise<k8sclient.AccessSet>;

export function CancelDrawerSnapshot(arg1:string):Promise<void>;

export function CancelPortForwardStart(arg1:string):Promise<void>;

export function CancelViewReads():Promise<number>;

export function ChartDefaultValues(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ChartDetails(arg1:string,arg2:string):Promise<k8sclient.ChartDetail>;

export function CheckTrafficPolicy(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string):Promise<k8sclient.TrafficCheckResult>;

export function ClusterChecks(arg1:string):Promise<k8sclient.ClusterChecksReport>;

export function ClusterEvents(arg1:number):Promise<Array<k8sclient.EventInfo>>;

export function ClusterHygiene(arg1:string):Promise<k8sclient.HygieneReport>;

export function ClusterStructure(arg1:string):Promise<k8sclient.ClusterStructureData>;

export function ConnectWithContent(arg1:string,arg2:string):Promise<void>;

export function ConnectWithPath(arg1:string,arg2:string):Promise<void>;

export function ConnectedClusters():Promise<Array<main.ClusterInfo>>;

export function ContextsFromContent(arg1:string):Promise<main.ContextsResult>;

export function ContextsFromPath(arg1:string):Promise<main.ContextsResult>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CustomKinds():Promise<k8sclient.CustomKindList>;

export function DeleteResourceOwned(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeploymentTree(arg1:string,arg2:string):Promise<k8sclient.RelationNode>;

export function Diagnostics(arg1:string):Promise<string>;

export function DisconnectCluster(arg1:string):Promise<string>;

export function DrainImpact(arg1:string):Promise<k8sclient.DrainImpact>;

export function DrainNodeOwned(arg1:string,arg2:string):Promise<void>;

export function ExecResize(arg1:number,arg2:number):Promise<void>;

export function ExecWrite(arg1:string):Promise<void>;

export function ExplainPodScheduling(arg1:string,arg2:string):Promise<k8sclient.SchedulingReport>;

export function ForgetConnection(arg1:string,arg2:string):Promise<void>;

export function GetAIConfig():Promise<main.AIConfigView>;

export function GetAIStatus():Promise<main.AIStatus>;

export function GetDetail(arg1:string,arg2:string,arg3:string):Promise<k8sclient.ResourceDetail>;

export function GetDrawerSnapshotOwned(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HelmGet(arg1:string,arg2:string):Promise<k8sclient.HelmReleaseDetail>;

export function HelmGetRevision(arg1:string,arg2:string,arg3:number):Promise<k8sclient.HelmReleaseDetail>;

export function HelmHistory(arg1:string,arg2:string):Promise<Array<k8sclient.HelmRevision>>;

export function HelmInstallOwned(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function HelmInstallPreview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<k8sclient.HelmDiff>;

export function HelmReleaseResources(arg1:string,arg2:string):Promise<Array<k8sclient.HelmResource>>;

export function HelmRollbackOwned(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function HelmSnapshot(arg1:string,arg2:string):Promise<k8sclient.HelmReleaseSnapshot>;

export function HelmTestOwned(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HelmUninstallOwned(arg1:string,arg2:string,arg3:string):Promise<void>;

export function HelmUpgradePreview(arg1:string,arg2:string,arg3:string):Promise<k8sclient.HelmDiff>;

export function HelmUpgradeValuesOwned(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<void>;

export function IngressTree(arg1:string,arg2:string):Promise<k8sclient.RelationNode>;

export function InvestigateResource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListCRDs():Promise<Array<k8sclient.CRDInfo>>;

export function ListClusterRoleBindings():Promise<Array<k8sclient.ClusterRoleBindingInfo>>;

export function ListClusterRoles():Promise<Array<k8sclient.ClusterRoleInfo>>;

export function ListConfigMaps(arg1:string):Promise<Array<k8sclient.ConfigMapInfo>>;

export function ListCronJobs(arg1:string):Promise<Array<k8sclient.CronJobInfo>>;

export function ListCustom(arg1:string,arg2:string):Promise<Array<k8sclient.CustomObject>>;

export function ListCustomPage(arg1:string,arg2:string,arg3:string,arg4:number):Promise<k8sclient.CustomObjectPage>;

export function ListDaemonSets(arg1:string):Promise<Array<k8sclient.DaemonSetInfo>>;

export function ListDeployments(arg1:string):Promise<Array<k8sclient.DeploymentInfo>>;

export function ListEvents(arg1:string,arg2:string,arg3:string):Promise<Array<k8sclient.EventInfo>>;

export function ListHelmReleases(arg1:string):Promise<Array<k8sclient.HelmReleaseInfo>>;

export function ListHelmRepos():Promise<Array<k8sclient.HelmRepo>>;

export function ListHorizontalPodAutoscalers(arg1:string):Promise<Array<k8sclient.HPAInfo>>;

export function ListIngresses(arg1:string):Promise<Array<k8sclient.IngressInfo>>;

export function ListJobs(arg1:string):Promise<Array<k8sclient.JobInfo>>;

export function ListLimitRanges(arg1:string):Promise<Array<k8sclient.LimitRangeInfo>>;

export function ListNamespaces():Promise<Array<k8sclient.NamespaceInfo>>;

export function ListNetworkPolicies(arg1:string):Promise<Array<k8sclient.NetworkPolicyInfo>>;

export function ListNodes():Promise<Array<k8sclient.NodeInfo>>;

export function ListPVCs(arg1:string):Promise<Array<k8sclient.PVCInfo>>;

export function ListPersistentVolumes():Promise<Array<k8sclient.PersistentVolumeInfo>>;

export function ListPodDisruptionBudgets(arg1:string):Promise<Array<k8sclient.PDBInfo>>;

export function ListPods(arg1:string):Promise<Array<k8sclient.PodInfo>>;

export function ListPortForwards():Promise<Array<main.PortForwardInfo>>;

export function ListResourceQuotas(arg1:string):Promise<Array<k8sclient.ResourceQuotaInfo>>;

export function ListRoleBindings(arg1:string):Promise<Array<k8sclient.RoleBindingInfo>>;

export function ListRoles(arg1:string):Promise<Array<k8sclient.RoleInfo>>;

export function ListSecrets(arg1:string):Promise<Array<k8sclient.SecretInfo>>;

export function ListServiceAccounts(arg1:string):Promise<Array<k8sclient.ServiceAccountInfo>>;

export function ListServices(arg1:string):Promise<Array<k8sclient.ServiceInfo>>;

export function ListStatefulSets(arg1:string):Promise<Array<k8sclient.StatefulSetInfo>>;

export function ListStorageClasses():Promise<Array<k8sclient.StorageClassInfo>>;

export function NamespaceSummary(arg1:string):Promise<Array<k8sclient.NsKindCount>>;

export function NetworkFlows(arg1:string):Promise<k8sclient.NetworkFlows>;

export function NodeMetrics():Promise<Array<k8sclient.NodeMetric>>;

export function OverviewSnapshot():Promise<k8sclient.OverviewData>;

export function PickKubeconfigFile():Promise<string>;

export function PlanApplyPermissions(arg1:string):Promise<k8sclient.PermissionPlan>;

export function PlanDrainPermissions(arg1:string):Promise<k8sclient.PermissionPlan>;

export function PlanHelmPermissions(arg1:string,arg2:string,arg3:string,arg4:number):Promise<k8sclient.PermissionPlan>;

export function PodContainerStates(arg1:string,arg2:string):Promise<Array<k8sclient.ContainerState>>;

export function PodContainers(arg1:string,arg2:string):Promise<Array<string>>;

export function PodLogs(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<string>;

export function PodMetricsList(arg1:string):Promise<Array<k8sclient.PodMetric>>;

export function PodsOnNode(arg1:string):Promise<Array<k8sclient.PodInfo>>;

export function PodsPage(arg1:string,arg2:string,arg3:number):Promise<k8sclient.PodsPage>;

export function PodsSnapshot(arg1:string):Promise<k8sclient.PodsSnapshot>;

export function RecentConnections():Promise<Array<main.RecentConnection>>;

export function RemoveHelmRepo(arg1:string):Promise<void>;

export function RestartDaemonSetOwned(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartDeploymentOwned(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartStatefulSetOwned(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RollbackDeploymentOwned(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function RolloutHistory(arg1:string,arg2:string):Promise<Array<k8sclient.RolloutRevision>>;

export function RunCronJobNowOwned(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveIncidentReport(arg1:string):Promise<string>;

export function SaveTextToFile(arg1:string,arg2:string):Promise<string>;

export function ScaleDeploymentOwned(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SearchCharts(arg1:string):Promise<Array<k8sclient.ChartSearchResult>>;

export function SearchResources(arg1:string):Promise<Array<k8sclient.SearchHit>>;

export function SecretData(arg1:string,arg2:string):Promise<Array<k8sclient.SecretEntry>>;

export function ServiceTree(arg1:string,arg2:string):Promise<k8sclient.RelationNode>;

export function SetDeploymentPausedOwned(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetNodeSchedulableOwned(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SidebarCounts(arg1:string,arg2:boolean):Promise<Array<k8sclient.NavCount>>;

export function Sizing(arg1:string):Promise<k8sclient.SizingReport>;

export function StartExec(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<string>;

export function StartLogStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartPortForward(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:boolean):Promise<main.PortForwardInfo>;

export function StopExec():Promise<void>;

export function StopLogStream():Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SwitchCluster(arg1:string):Promise<void>;

export function TopPods(arg1:number):Promise<Array<k8sclient.PodMetric>>;

export function UpdateHelmRepos():Promise<void>;

export function UpdateYAML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
