// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIResourceContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIResourceContext'](arg1, arg2, arg3);
}

export function AddHelmRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddHelmRepo'](arg1, arg2, arg3, arg4);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyPreview(arg1) {
  return window['go']['main']['App']['ApplyPreview'](arg1);
}

export function ApplyYAMLOwned(arg1, arg2) {
  return window['go']['main']['App']['ApplyYAMLOwned'](arg1, arg2);
}

export function AskAboutResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AskAboutResource'](arg1, arg2, arg3, arg4, arg5);
}

export function BrowseHelmRepo(arg1) {
  return window['go']['main']['App']['BrowseHelmRepo'](arg1);
}

export function CanI(arg1, arg2) {
  return window['go']['main']['App']['CanI'](arg1, arg2);
}

export function CancelDrawerSnapshot(arg1) {
  return window['go']['main']['App']['CancelDrawerSnapshot'](arg1);
}

export function CancelPortForwardStart(arg1) {
  return window['go']['main']['App']['CancelPortForwardStart'](arg1);
}

export function ChartDefaultValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChartDefaultValues'](arg1, arg2, arg3, arg4);
}

export function ChartDetails(arg1, arg2) {
  return window['go']['main']['App']['ChartDetails'](arg1, arg2);
}

export function ClusterEvents(arg1) {
  return window['go']['main']['App']['ClusterEvents'](arg1);
}

export function ClusterStructure(arg1) {
  return window['go']['main']['App']['ClusterStructure'](arg1);
}

export function ConnectWithContent(arg1, arg2) {
  return window['go']['main']['App']['ConnectWithContent'](arg1, arg2);
}

export function ConnectWithPath(arg1, arg2) {
  return window['go']['main']['App']['ConnectWithPath'](arg1, arg2);
}

export function ConnectedClusters() {
  return window['go']['main']['App']['ConnectedClusters']();
}

export function ContextsFromContent(arg1) {
  return window['go']['main']['App']['ContextsFromContent'](arg1);
}

export function ContextsFromPath(arg1) {
  return window['go']['main']['App']['ContextsFromPath'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CustomKinds() {
  return window['go']['main']['App']['CustomKinds']();
}

export function DeleteResourceOwned(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteResourceOwned'](arg1, arg2, arg3, arg4);
}

export function DeploymentTree(arg1, arg2) {
  return window['go']['main']['App']['DeploymentTree'](arg1, arg2);
}

export function Diagnostics(arg1) {
  return window['go']['main']['App']['Diagnostics'](arg1);
}

export function DisconnectCluster(arg1) {
  return window['go']['main']['App']['DisconnectCluster'](arg1);
}

export function DrainNodeOwned(arg1, arg2) {
  return window['go']['main']['App']['DrainNodeOwned'](arg1, arg2);
}

export function ExecResize(arg1, arg2) {
  return window['go']['main']['App']['ExecResize'](arg1, arg2);
}

export function ExecWrite(arg1) {
  return window['go']['main']['App']['ExecWrite'](arg1);
}

export function ForgetConnection(arg1, arg2) {
  return window['go']['main']['App']['ForgetConnection'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAIStatus() {
  return window['go']['main']['App']['GetAIStatus']();
}

export function GetDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDetail'](arg1, arg2, arg3);
}

export function GetDrawerSnapshotOwned(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetDrawerSnapshotOwned'](arg1, arg2, arg3, arg4, arg5);
}

export function GetYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetYAML'](arg1, arg2, arg3);
}

export function HelmGet(arg1, arg2) {
  return window['go']['main']['App']['HelmGet'](arg1, arg2);
}

export function HelmGetRevision(arg1, arg2, arg3) {
  return window['go']['main']['App']['HelmGetRevision'](arg1, arg2, arg3);
}

export function HelmHistory(arg1, arg2) {
  return window['go']['main']['App']['HelmHistory'](arg1, arg2);
}

export function HelmInstallOwned(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['HelmInstallOwned'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function HelmInstallPreview(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['HelmInstallPreview'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function HelmReleaseResources(arg1, arg2) {
  return window['go']['main']['App']['HelmReleaseResources'](arg1, arg2);
}

export function HelmRollbackOwned(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HelmRollbackOwned'](arg1, arg2, arg3, arg4);
}

export function HelmSnapshot(arg1, arg2) {
  return window['go']['main']['App']['HelmSnapshot'](arg1, arg2);
}

export function HelmTestOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['HelmTestOwned'](arg1, arg2, arg3);
}

export function HelmUninstallOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['HelmUninstallOwned'](arg1, arg2, arg3);
}

export function HelmUpgradePreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['HelmUpgradePreview'](arg1, arg2, arg3);
}

export function HelmUpgradeValuesOwned(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['HelmUpgradeValuesOwned'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function IngressTree(arg1, arg2) {
  return window['go']['main']['App']['IngressTree'](arg1, arg2);
}

export function InvestigateResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvestigateResource'](arg1, arg2, arg3);
}

export function ListCRDs() {
  return window['go']['main']['App']['ListCRDs']();
}

export function ListClusterRoleBindings() {
  return window['go']['main']['App']['ListClusterRoleBindings']();
}

export function ListClusterRoles() {
  return window['go']['main']['App']['ListClusterRoles']();
}

export function ListConfigMaps(arg1) {
  return window['go']['main']['App']['ListConfigMaps'](arg1);
}

export function ListCronJobs(arg1) {
  return window['go']['main']['App']['ListCronJobs'](arg1);
}

export function ListCustom(arg1, arg2) {
  return window['go']['main']['App']['ListCustom'](arg1, arg2);
}

export function ListCustomPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListCustomPage'](arg1, arg2, arg3, arg4);
}

export function ListDaemonSets(arg1) {
  return window['go']['main']['App']['ListDaemonSets'](arg1);
}

export function ListDeployments(arg1) {
  return window['go']['main']['App']['ListDeployments'](arg1);
}

export function ListEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListEvents'](arg1, arg2, arg3);
}

export function ListHelmReleases(arg1) {
  return window['go']['main']['App']['ListHelmReleases'](arg1);
}

export function ListHelmRepos() {
  return window['go']['main']['App']['ListHelmRepos']();
}

export function ListIngresses(arg1) {
  return window['go']['main']['App']['ListIngresses'](arg1);
}

export function ListJobs(arg1) {
  return window['go']['main']['App']['ListJobs'](arg1);
}

export function ListLimitRanges(arg1) {
  return window['go']['main']['App']['ListLimitRanges'](arg1);
}

export function ListNamespaces() {
  return window['go']['main']['App']['ListNamespaces']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function ListPVCs(arg1) {
  return window['go']['main']['App']['ListPVCs'](arg1);
}

export function ListPersistentVolumes() {
  return window['go']['main']['App']['ListPersistentVolumes']();
}

export function ListPods(arg1) {
  return window['go']['main']['App']['ListPods'](arg1);
}

export function ListPortForwards() {
  return window['go']['main']['App']['ListPortForwards']();
}

export function ListResourceQuotas(arg1) {
  return window['go']['main']['App']['ListResourceQuotas'](arg1);
}

export function ListRoleBindings(arg1) {
  return window['go']['main']['App']['ListRoleBindings'](arg1);
}

export function ListRoles(arg1) {
  return window['go']['main']['App']['ListRoles'](arg1);
}

export function ListSecrets(arg1) {
  return window['go']['main']['App']['ListSecrets'](arg1);
}

export function ListServiceAccounts(arg1) {
  return window['go']['main']['App']['ListServiceAccounts'](arg1);
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ListStatefulSets(arg1) {
  return window['go']['main']['App']['ListStatefulSets'](arg1);
}

export function ListStorageClasses() {
  return window['go']['main']['App']['ListStorageClasses']();
}

export function NamespaceSummary(arg1) {
  return window['go']['main']['App']['NamespaceSummary'](arg1);
}

export function NetworkFlows(arg1) {
  return window['go']['main']['App']['NetworkFlows'](arg1);
}

export function NodeMetrics() {
  return window['go']['main']['App']['NodeMetrics']();
}

export function OverviewSnapshot() {
  return window['go']['main']['App']['OverviewSnapshot']();
}

export function PickKubeconfigFile() {
  return window['go']['main']['App']['PickKubeconfigFile']();
}

export function PlanApplyPermissions(arg1) {
  return window['go']['main']['App']['PlanApplyPermissions'](arg1);
}

export function PlanDrainPermissions(arg1) {
  return window['go']['main']['App']['PlanDrainPermissions'](arg1);
}

export function PlanHelmPermissions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlanHelmPermissions'](arg1, arg2, arg3, arg4);
}

export function PodContainers(arg1, arg2) {
  return window['go']['main']['App']['PodContainers'](arg1, arg2);
}

export function PodLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PodLogs'](arg1, arg2, arg3, arg4);
}

export function PodMetricsList(arg1) {
  return window['go']['main']['App']['PodMetricsList'](arg1);
}

export function PodsOnNode(arg1) {
  return window['go']['main']['App']['PodsOnNode'](arg1);
}

export function PodsPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['PodsPage'](arg1, arg2, arg3);
}

export function PodsSnapshot(arg1) {
  return window['go']['main']['App']['PodsSnapshot'](arg1);
}

export function RecentConnections() {
  return window['go']['main']['App']['RecentConnections']();
}

export function RemoveHelmRepo(arg1) {
  return window['go']['main']['App']['RemoveHelmRepo'](arg1);
}

export function RestartDaemonSetOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartDaemonSetOwned'](arg1, arg2, arg3);
}

export function RestartDeploymentOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartDeploymentOwned'](arg1, arg2, arg3);
}

export function RestartStatefulSetOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartStatefulSetOwned'](arg1, arg2, arg3);
}

export function RollbackDeploymentOwned(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RollbackDeploymentOwned'](arg1, arg2, arg3, arg4);
}

export function RolloutHistory(arg1, arg2) {
  return window['go']['main']['App']['RolloutHistory'](arg1, arg2);
}

export function RunCronJobNowOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCronJobNowOwned'](arg1, arg2, arg3);
}

export function SaveAIConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveIncidentReport(arg1) {
  return window['go']['main']['App']['SaveIncidentReport'](arg1);
}

export function SaveTextToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextToFile'](arg1, arg2);
}

export function ScaleDeploymentOwned(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScaleDeploymentOwned'](arg1, arg2, arg3, arg4);
}

export function SearchCharts(arg1) {
  return window['go']['main']['App']['SearchCharts'](arg1);
}

export function SearchResources(arg1) {
  return window['go']['main']['App']['SearchResources'](arg1);
}

export function SecretData(arg1, arg2) {
  return window['go']['main']['App']['SecretData'](arg1, arg2);
}

export function ServiceTree(arg1, arg2) {
  return window['go']['main']['App']['ServiceTree'](arg1, arg2);
}

export function SetDeploymentPausedOwned(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetDeploymentPausedOwned'](arg1, arg2, arg3, arg4);
}

export function SetNodeSchedulableOwned(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNodeSchedulableOwned'](arg1, arg2, arg3);
}

export function SidebarCounts(arg1, arg2) {
  return window['go']['main']['App']['SidebarCounts'](arg1, arg2);
}

export function Sizing(arg1) {
  return window['go']['main']['App']['Sizing'](arg1);
}

export function StartExec(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartExec'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartLogStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLogStream'](arg1, arg2, arg3, arg4);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StopExec() {
  return window['go']['main']['App']['StopExec']();
}

export function StopLogStream() {
  return window['go']['main']['App']['StopLogStream']();
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function SwitchCluster(arg1) {
  return window['go']['main']['App']['SwitchCluster'](arg1);
}

export function TopPods(arg1) {
  return window['go']['main']['App']['TopPods'](arg1);
}

export function UpdateHelmRepos() {
  return window['go']['main']['App']['UpdateHelmRepos']();
}

export function UpdateYAML(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateYAML'](arg1, arg2, arg3, arg4, arg5);
}
