// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k8sclient} from '../models';
import {main} from '../models';

export function AIResourceContext(arg1:string,arg2:string,arg3:string):Promise<k8sclient.AIContext>;

export function AddHelmRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AppVersion():Promise<string>;

export function ApplyPreview(arg1:string):Promise<k8sclient.ApplyDiff>;

export function ApplyYAML(arg1:string):Promise<string>;

export function AskAboutResource(arg1:string,arg2:string,arg3:string,arg4:Array<main.AIMessage>):Promise<string>;

export function BrowseHelmRepo(arg1:string):Promise<Array<k8sclient.ChartSearchResult>>;

export function CanI(arg1:string,arg2:string):Promise<k8sclient.AccessSet>;

export function ChartDefaultValues(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ChartDetails(arg1:string,arg2:string):Promise<k8sclient.ChartDetail>;

export function ClusterEvents(arg1:number):Promise<Array<k8sclient.EventInfo>>;

export function ConnectWithContent(arg1:string,arg2:string):Promise<void>;

export function ConnectWithPath(arg1:string,arg2:string):Promise<void>;

export function ConnectedClusters():Promise<Array<main.ClusterInfo>>;

export function ContextsFromContent(arg1:string):Promise<main.ContextsResult>;

export function ContextsFromPath(arg1:string):Promise<main.ContextsResult>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CustomKinds():Promise<k8sclient.CustomKindList>;

export function DeleteResource(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeploymentTree(arg1:string,arg2:string):Promise<k8sclient.RelationNode>;

export function Diagnostics(arg1:string):Promise<string>;

export function DisconnectCluster(arg1:string):Promise<string>;

export function DrainNode(arg1:string):Promise<void>;

export function ExecWrite(arg1:string):Promise<void>;

export function ForgetConnection(arg1:string,arg2:string):Promise<void>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetAIStatus():Promise<main.AIStatus>;

export function GetDetail(arg1:string,arg2:string,arg3:string):Promise<k8sclient.ResourceDetail>;

export function GetYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HelmGet(arg1:string,arg2:string):Promise<k8sclient.HelmReleaseDetail>;

export function HelmGetRevision(arg1:string,arg2:string,arg3:number):Promise<k8sclient.HelmReleaseDetail>;

export function HelmHistory(arg1:string,arg2:string):Promise<Array<k8sclient.HelmRevision>>;

export function HelmInstall(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function HelmInstallPreview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<k8sclient.HelmDiff>;

export function HelmReleaseResources(arg1:string,arg2:string):Promise<Array<k8sclient.HelmResource>>;

export function HelmRollback(arg1:string,arg2:string,arg3:number):Promise<void>;

export function HelmTest(arg1:string,arg2:string):Promise<string>;

export function HelmUninstall(arg1:string,arg2:string):Promise<void>;

export function HelmUpgradePreview(arg1:string,arg2:string,arg3:string):Promise<k8sclient.HelmDiff>;

export function HelmUpgradeValues(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IngressTree(arg1:string,arg2:string):Promise<k8sclient.RelationNode>;

export function ListCRDs():Promise<Array<k8sclient.CRDInfo>>;

export function ListClusterRoleBindings():Promise<Array<k8sclient.ClusterRoleBindingInfo>>;

export function ListClusterRoles():Promise<Array<k8sclient.ClusterRoleInfo>>;

export function ListConfigMaps(arg1:string):Promise<Array<k8sclient.ConfigMapInfo>>;

export function ListCronJobs(arg1:string):Promise<Array<k8sclient.CronJobInfo>>;

export function ListCustom(arg1:string,arg2:string):Promise<Array<k8sclient.CustomObject>>;

export function ListDaemonSets(arg1:string):Promise<Array<k8sclient.DaemonSetInfo>>;

export function ListDeployments(arg1:string):Promise<Array<k8sclient.DeploymentInfo>>;

export function ListEvents(arg1:string,arg2:string,arg3:string):Promise<Array<k8sclient.EventInfo>>;

export function ListHelmReleases(arg1:string):Promise<Array<k8sclient.HelmReleaseInfo>>;

export function ListHelmRepos():Promise<Array<k8sclient.HelmRepo>>;

export function ListIngresses(arg1:string):Promise<Array<k8sclient.IngressInfo>>;

export function ListJobs(arg1:string):Promise<Array<k8sclient.JobInfo>>;

export function ListLimitRanges(arg1:string):Promise<Array<k8sclient.LimitRangeInfo>>;

export function ListNamespaces():Promise<Array<k8sclient.NamespaceInfo>>;

export function ListNodes():Promise<Array<k8sclient.NodeInfo>>;

export function ListPVCs(arg1:string):Promise<Array<k8sclient.PVCInfo>>;

export function ListPersistentVolumes():Promise<Array<k8sclient.PersistentVolumeInfo>>;

export function ListPods(arg1:string):Promise<Array<k8sclient.PodInfo>>;

export function ListPortForwards():Promise<Array<main.PortForwardInfo>>;

export function ListResourceQuotas(arg1:string):Promise<Array<k8sclient.ResourceQuotaInfo>>;

export function ListRoleBindings(arg1:string):Promise<Array<k8sclient.RoleBindingInfo>>;

export function ListRoles(arg1:string):Promise<Array<k8sclient.RoleInfo>>;

export function ListSecrets(arg1:string):Promise<Array<k8sclient.SecretInfo>>;

export function ListServiceAccounts(arg1:string):Promise<Array<k8sclient.ServiceAccountInfo>>;

export function ListServices(arg1:string):Promise<Array<k8sclient.ServiceInfo>>;

export function ListStatefulSets(arg1:string):Promise<Array<k8sclient.StatefulSetInfo>>;

export function ListStorageClasses():Promise<Array<k8sclient.StorageClassInfo>>;

export function NamespaceSummary(arg1:string):Promise<Array<k8sclient.NsKindCount>>;

export function NetworkFlows(arg1:string):Promise<k8sclient.NetworkFlows>;

export function NodeMetrics():Promise<Array<k8sclient.NodeMetric>>;

export function PickKubeconfigFile():Promise<string>;

export function PodContainers(arg1:string,arg2:string):Promise<Array<string>>;

export function PodLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function PodMetricsList(arg1:string):Promise<Array<k8sclient.PodMetric>>;

export function PodsOnNode(arg1:string):Promise<Array<k8sclient.PodInfo>>;

export function RecentConnections():Promise<Array<main.RecentConnection>>;

export function RemoveHelmRepo(arg1:string):Promise<void>;

export function RestartDaemonSet(arg1:string,arg2:string):Promise<void>;

export function RestartDeployment(arg1:string,arg2:string):Promise<void>;

export function RestartStatefulSet(arg1:string,arg2:string):Promise<void>;

export function RollbackDeployment(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RolloutHistory(arg1:string,arg2:string):Promise<Array<k8sclient.RolloutRevision>>;

export function RunCronJobNow(arg1:string,arg2:string):Promise<void>;

export function SaveAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveTextToFile(arg1:string,arg2:string):Promise<string>;

export function ScaleDeployment(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SearchCharts(arg1:string):Promise<Array<k8sclient.ChartSearchResult>>;

export function SearchResources(arg1:string):Promise<Array<k8sclient.SearchHit>>;

export function SecretData(arg1:string,arg2:string):Promise<Array<k8sclient.SecretEntry>>;

export function ServiceTree(arg1:string,arg2:string):Promise<k8sclient.RelationNode>;

export function SetDeploymentPaused(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetNodeSchedulable(arg1:string,arg2:boolean):Promise<void>;

export function SidebarCounts(arg1:string,arg2:boolean):Promise<Array<k8sclient.NavCount>>;

export function Sizing(arg1:string):Promise<k8sclient.SizingReport>;

export function StartExec(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartLogStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartPortForward(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.PortForwardInfo>;

export function StopExec():Promise<void>;

export function StopLogStream():Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SwitchCluster(arg1:string):Promise<void>;

export function TopPods(arg1:number):Promise<Array<k8sclient.PodMetric>>;

export function UpdateHelmRepos():Promise<void>;

export function UpdateYAML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
